organization          = "your_organization"
workspace             = "your_workspace"
AWS_ACCESS_KEY_ID     = "your_access_key"
AWS_SECRET_ACCESS_KEY = "your_secret_key"
instance_ami          = "ami-078296f82eb463377" # linux AMI
instance_type         = "t2.micro"
instance_key          = "your_instance_key"
region                = "us-east-1"
availability_zone     = "us-east-1a"
subnets_cidr_block    = ["10.0.1.0/24", "10.0.2.0/24"]
